# Generated by Django 5.1.1 on 2024-09-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
    ]
