# Generated by Django 5.1.1 on 2024-09-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NearbyPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby_pincodes', models.JSONField()),
                ('base_pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pincode_app.pincode')),
            ],
        ),
    ]
