# Generated by Django 5.1.1 on 2024-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode_app', '0003_remove_nearbypincode_nearby_pincodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='pincode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
